export default [
  {
    "_id": 123,
    "topic": "Space",
    "userName": "SpaceX",
    "handle": "spacex",
    "time": "2h",
    "image": "../../../images/spacexlogo.jpeg",
    "title": "SpaceX's Mission",
    "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
    "logo": "../../../images/spacexlogo.jpeg",
    "liked": true,
    "likes": 2345,
    "dislikes": 134,
    "comments": 1212,
    "replies": 123,
    "retuits": 432
  },
  {
    "_id": 234,
    "topic": "Traffic",
    "userName": "The Boring Company",
    "handle": "boringcompany",
    "time": "2h",
    "image": "../../../images/theBoringCompany.webp",
    "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
    "tuit": "The Boring Company (TBC) is an American infrastructure and tunnel construction services company founded by Elon Musk. Its ongoing and proposed projects are designed for intra-city ('loop') transit systems.",
    "logo": "../../../images/theBoringCompany.webp",
    "liked": true,
    "likes": 2345,
    "dislikes": 234,
    "comments": 1333,
    "replies": 123,
    "retuits": 432
  },
];
